### ISSUE TITLE
Add cat nodes command

### ISSUE THREAD

**Issue by m4ver1k** [esctl/esctl#15]
esctl cat nodes

https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html
https://pkg.go.dev/github.com/elastic/go-elasticsearch@v0.0.0/esapi#CatNodesRequest

**Comment by m4ver1k** [comment]
Yes that would do to start with. Unless you want to take that up as a param

**Comment by jijotj** [comment]
Cool lets start with the default columns. Additional params can be added as and when required.

**Comment by jijotj** [comment]
Actually, my bad. The cat APIs are only meant for human/dashboard consumption ([ref](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/cat.html#intro)). They don't talk JSON 😞. I think we'll have to use /_nodes and select fields we need from it. 

API reference for /_nodes: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html
