### ISSUE TITLE
Add support to get index settings

### ISSUE THREAD

**Issue by m4ver1k** [esctl/esctl#22]
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-settings.html

`esctl index settings`

```
"settings": {
            "index": {
                "creation_date": "1588545932934",
                "number_of_replicas": "2",
                "number_of_shards": "1",
                "provided_name": "indexName",
                "uuid": "asdasdasd-adasdads",
                "version": {
                    "created": "7050099"
                }
            }
        }
```

**Comment by jijotj** [comment]
If there are multiple indices, we'd need a flag/parameter to filter by index right? Should the command return all indices by default?

**Comment by m4ver1k** [comment]
@jijotj we can add a flag to specify the index of interest.
Returning all might be noisy in certain cases. But if that is needed we can specify the target as `_all` 
What do you think ?

**Comment by jijotj** [comment]
Yea, sounds good 👍

**Comment by m4ver1k** [comment]
@jijotj are you picking this up ?

**Comment by jijotj** [comment]
Yea missed assigning it to me. I can do #21 as well as both deal with indexes.

**Comment by m4ver1k** [comment]
Go for it
